### ISSUE TITLE
[BUG] Uhr geht ca. eine Sekunde nach

### ISSUE THREAD

**Issue by Ronja11** [Zagrthos/UsefulTools#26]
**Beschreibung des Bugs**
Uhr geht ca. eine Sekunde nach im vergleich zur Windows Uhr.

**Zum Reproduzieren**
Uhr öffnen

**Erwartetes Verhalten**
Selbe Zeit

**Weitere Informationen**
Auch nach neuem sync der Windows Uhr

**Comment by Zagrthos** [comment]
Fixed.
