### ISSUE TITLE
[BUG] TR Auswahlfenster Buttonskalierung

### ISSUE THREAD

**Issue by Ronja11** [Zagrthos/UsefulTools#27]
**Beschreibung des Bugs**
Wenn man das Fenster skaliert, verschwinden Buttons anstatt sich anzupassen obwohl noch platz ist.

**Zum Reproduzieren**
Schritte um diesen Bug zu reproduzieren:
Fenster skalieren.

**Erwartetes Verhalten**
Buttons bleiben sichtbar

**Screenshots**
![image](https://user-images.githubusercontent.com/40367168/128537290-14753ae7-7500-4c64-bddb-319beb287192.png)

**Comment by Zagrthos** [comment]
Schon gefixed.
