### ISSUE TITLE
[BUG] Darkmode Schriftfarbe Ergebnis

### ISSUE THREAD

**Issue by Ronja11** [Zagrthos/UsefulTools#29]
**Beschreibung des Bugs**
Im Darkmode bleibt die Schrift fürs Ergebnis nach einer Fehlermeldung rot.

**Zum Reproduzieren**
Schritte um diesen Bug zu reproduzieren:
1. Fehler provozieren
2. Richtige Rechnung machen

**Erwartetes Verhalten**
Weißes Ergebnis

**Screenshots**
![image](https://user-images.githubusercontent.com/40367168/128539725-ab4e639c-cb78-4e6f-94fc-89f17637fdb0.png)

**Comment by Zagrthos** [comment]
Das ist Absicht -> Fehlermeldungen sind rot und sollen sich von den Allgemeinen Texten abheben. Kann aber gerne die Farbe etwas heller machen.

**Comment by Ronja11** [comment]
Das Problem ist, dass danach auch alle richtigen Ergebnisse rot sind

**Comment by Zagrthos** [comment]
Fixed.
