### ISSUE TITLE
[BUG] Darkmode sync

### ISSUE THREAD

**Issue by Ronja11** [Zagrthos/UsefulTools#30]
**Beschreibung des Bugs**
Felder im Menü werden beim drüber hovern dunkel.

**Zum Reproduzieren**
Schritte um diesen Bug zu reproduzieren:
1. Taschenrechner Auswahl öffnen
2. In TR Auswahl darkmode einstellen
3. In Hauptmenü über Leiste hovern oder menüs öffnen

**Erwartetes Verhalten**
Design in Main bleibt gleich oder wird automatisch direkt zum darkmode geändert.

**Screenshots**
![image](https://user-images.githubusercontent.com/40367168/128540297-c52e91bd-99cd-4d52-a2f3-187d9fa73c47.png)
![image](https://user-images.githubusercontent.com/40367168/128540385-bbe9792d-731c-4736-b8f9-7eca919594a6.png)

**Comment by Zagrthos** [comment]
Fixed.
